name: iota-cooler
version: '1.1'
summary: IOTAcooler, the IOTA Cold Transaction Signer 
description: |
  A cross-platform cold storage and spending wallet for the IOTA crypto currency.

icon: gui/iotacooler.png
grade: stable
confinement: strict
base: core18 # based on ubuntu 18.04 LTS

apps:
  iota-cooler:
    command: desktop-launch $SNAP/opt/iotacooler/usr/bin/iota-cooler
    desktop: usr/share/applications/iotacooler.desktop
    environment:
      DISABLE_WAYLAND: 1
    plugs:
      - home
      - network
      - opengl
      - removable-media
      - unity7
      - x11
      - wayland
      - desktop
      - desktop-legacy

parts:
  iota-cooler:
    source: https://github.com/joshirio/iota-cooler/releases/download/v1.1/iotacooler-1.1-x86_64.deb
    plugin: dump
    source-type: deb
    override-build: |
      snapcraftctl build
      #fix icon path
      sed -i 's|Icon=iotacooler|Icon=${SNAP}/usr/share/pixmaps/iotacooler.png|g' $SNAPCRAFT_PART_INSTALL/usr/share/applications/iotacooler.desktop
    stage-packages:
      - dbus
    after: [desktop-qt5]

  desktop-qt5: # custom define becasue no remote parts are supported when using a base (at least not on 16.04), https://github.com/ubuntu/snapcraft-desktop-helpers
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
